'use client';

import { useEffect, useState, use } from 'react';
import Link from 'next/link';
import styles from './ledger.module.css';
import { getWorkers, getWorkerBalance, getWorkerLedger, Worker } from '@/lib/storage';

interface Props {
  params: Promise<{ id: string }>;
}

export default function WorkerLedgerPage({ params }: Props) {
  const { id } = use(params);
  const [worker, setWorker] = useState<Worker | undefined>();
  const [ledger, setLedger] = useState<any[]>([]);
  const [balance, setBalance] = useState<any>(null);

  useEffect(() => {
    const w = getWorkers().find(worker => worker.id === id);
    if (w) {
      setWorker(w);
      setLedger(getWorkerLedger(id));
      setBalance(getWorkerBalance(id));
    }
  }, [id]);

  if (!worker) return <div className="container flex-center" style={{ height: '50vh' }}>Worker not found.</div>;

  const shareToWhatsApp = () => {
    const text = `*Worker Ledger: ${worker.name}*\n` +
                 `Role: ${worker.role}\n` +
                 `--------------------------\n` +
                 `Days Worked: ${balance.daysWorked}\n` +
                 `Total Earned: ₹${balance.earned}\n` +
                 `Total Paid: ₹${balance.paid}\n` +
                 `*Balance Due: ₹${balance.balance}*\n` +
                 `--------------------------\n` +
                 `Generated by BahiKhata`;
    
    window.open(`https://wa.me/?text=${encodeURIComponent(text)}`);
  };

  const exportPDF = async () => {
    const { jsPDF } = await import('jspdf');
    const { default: autoTable } = await import('jspdf-autotable');
    
    const doc = new jsPDF();
    
    // Header
    doc.setFontSize(20);
    doc.text('Labour Payment Statement', 14, 22);
    
    doc.setFontSize(12);
    doc.setTextColor(100);
    doc.text(`Worker Name: ${worker.name}`, 14, 32);
    doc.text(`Role: ${worker.role}`, 14, 38);
    doc.text(`Daily Rate: Rs. ${worker.dailyRate}`, 14, 44);
    doc.text(`Statement Date: ${new Date().toLocaleDateString()}`, 14, 50);

    // Summary Box
    doc.setDrawColor(200);
    doc.setFillColor(245, 245, 245);
    doc.rect(14, 58, 182, 30, 'F');
    doc.setTextColor(0);
    doc.setFont('', 'bold');
    doc.text(`Total Days Worked: ${balance.daysWorked}`, 20, 68);
    doc.text(`Total Earned: Rs. ${balance.earned}`, 20, 76);
    doc.text(`Total Paid: Rs. ${balance.paid}`, 100, 68);
    doc.text(`BALANCE DUE: Rs. ${balance.balance}`, 100, 76);

    // Table
    const tableData = ledger.map(item => {
      let desc = '';
      let amt = 0;
      if (item.type === 'attendance') {
        desc = `Worked at ${item.project} (${item.status})`;
        if (item.overtimeAmount > 0) desc += ` + OT ₹${item.overtimeAmount}`;
        amt = (item.status === 'Half' ? worker.dailyRate / 2 : worker.dailyRate) + (item.overtimeAmount || 0);
      } else {
        desc = 'Payment Received';
        amt = -item.amount;
      }

      return [
        new Date(item.date).toLocaleDateString(),
        item.type === 'attendance' ? 'Work Day' : 'Payment',
        desc,
        item.notes || '-',
        amt > 0 ? `+ ${amt}` : `${amt}`
      ];
    });

    autoTable(doc, {
      startY: 95,
      head: [['Date', 'Type', 'Description', 'Notes', 'Amount (Rs.)']],
      body: tableData,
      theme: 'grid',
      headStyles: { fillColor: [40, 40, 40] },
      columnStyles: { 4: { halign: 'right', fontStyle: 'bold' } }
    });

    doc.save(`${worker.name.replace(/\s+/g, '_')}_Ledger.pdf`);
  };

  const exportExcel = async () => {
    const XLSX = await import('xlsx');
    
    const data = [
      ['Labour Payment Statement'],
      [`Worker: ${worker.name}`, '', '', `Daily Rate: ${worker.dailyRate}`],
      [`Role: ${worker.role}`, '', '', `Report Date: ${new Date().toLocaleDateString()}`],
      [],
      ['Summary'],
      ['Total Days', balance.daysWorked, 'Total Paid', balance.paid],
      ['Total Earned', balance.earned, 'BALANCE DUE', balance.balance],
      [],
      ['Transaction History'],
      ['Date', 'Type', 'Description', 'Notes', 'Amount']
    ];

    ledger.forEach(item => {
      let amt = 0;
      let desc = '';
      if (item.type === 'attendance') {
        desc = `${item.project} (${item.status})`;
        if (item.overtimeAmount > 0) desc += ` + OT ₹${item.overtimeAmount}`;
        amt = (item.status === 'Half' ? worker.dailyRate / 2 : worker.dailyRate) + (item.overtimeAmount || 0);
      } else {
        desc = 'Payment Received';
        amt = -item.amount;
      }

      data.push([
        new Date(item.date).toLocaleDateString(),
        item.type === 'attendance' ? 'Work Day' : 'Payment',
        desc,
        item.notes || '-',
        amt
      ]);
    });

    const ws = XLSX.utils.aoa_to_sheet(data);
    const wb = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(wb, ws, "Ledger");
    XLSX.writeFile(wb, `${worker.name.replace(/\s+/g, '_')}_Ledger.xlsx`);
  };

  return (
    <div className="container fade-in" style={{ paddingTop: '3rem', paddingBottom: '5rem' }}>
      <header className={styles.header}>
        <div>
          <Link href="/workers" className={styles.backLink}>← Back to Workers</Link>
          <h1 className="section-title" style={{ marginTop: '1rem', marginBottom: '0.5rem' }}>{worker.name}</h1>
          <p className={styles.role}>{worker.role} • ₹{worker.dailyRate}/day</p>
        </div>
        <div className={styles.headerActions}>
           <button className="btn-primary" onClick={shareToWhatsApp} style={{ background: '#25D366', color: '#fff' }}>
            <span>📱</span> WhatsApp
           </button>
           <button className="btn-secondary" onClick={exportPDF}>
            <span>📄</span> Export PDF
           </button>
           <button className="btn-secondary" onClick={exportExcel}>
            <span>📊</span> Export Excel
           </button>
        </div>
      </header>

      <div className={styles.summaryGrid}>
        <div className="card">
          <span>Earned</span>
          <h3>₹{balance?.earned}</h3>
        </div>
        <div className="card">
          <span>Paid</span>
          <h3>₹{balance?.paid}</h3>
        </div>
        <div className={`${styles.balanceCard} card`}>
          <span>Balance Due</span>
          <h3>₹{balance?.balance}</h3>
        </div>
      </div>

      <section className={styles.ledgerSection}>
        <h2 style={{ marginBottom: '1.5rem', fontSize: '1.25rem' }}>Transaction History</h2>
        <div className={styles.ledgerList}>
          {ledger.map((item, idx) => {
            const isAttendance = item.type === 'attendance';
            const dayValue = isAttendance 
              ? (item.status === 'Half' ? worker.dailyRate / 2 : worker.dailyRate) + (item.overtimeAmount || 0)
              : item.amount;

            return (
              <div key={idx} className={`${styles.ledgerItem} glass`}>
                <div className={styles.dateCol}>
                  <p className={styles.date}>{new Date(item.date).toLocaleDateString()}</p>
                  <span className={`${styles.typeBadge} ${isAttendance ? styles.work : styles.payment}`}>
                    {isAttendance ? 'Work Day' : 'Payment'}
                  </span>
                  {isAttendance && (
                    <span className={`${styles.statusSmall} ${item.status === 'Half' ? styles.half : ''}`}>
                      {item.status}
                    </span>
                  )}
                </div>
                <div className={styles.infoCol}>
                   {isAttendance ? (
                     <p>Worked at <strong>{item.project}</strong> {item.overtimeAmount > 0 && `(+₹${item.overtimeAmount} OT)`}</p>
                   ) : (
                     <p>Payment received</p>
                   )}
                   {item.notes && <p className={styles.notes}>"{item.notes}"</p>}
                   {item.image && (
                      <div className={styles.attachment}>
                        <img src={item.image} alt="Proof" onClick={() => window.open(item.image)} />
                      </div>
                   )}
                </div>
                <div className={styles.amountCol}>
                  <p className={isAttendance ? styles.plus : styles.minus}>
                    {isAttendance ? `+₹${dayValue}` : `-₹${dayValue}`}
                  </p>
                </div>
              </div>
            );
          })}
        </div>
      </section>
    </div>
  );
}
